import { TradingSymbolDef } from './tradingMarketData';

export const SYMBOL_CATEGORIES = [
  { key: 'crypto',      label: 'Crypto'          },
  { key: 'forex',       label: 'Forex'           },
  { key: 'commodities', label: 'Matières 1ères'  },
  { key: 'stocks',      label: 'Actions'         },
];

export function getLocalizedCategories(lang: string) {
  return [
    { key: 'crypto',      label: 'Crypto'                                    },
    { key: 'forex',       label: 'Forex'                                     },
    { key: 'commodities', label: lang === 'en' ? 'Commodities' : 'Matières 1ères' },
    { key: 'stocks',      label: lang === 'en' ? 'Stocks'      : 'Actions'        },
  ];
}

export function getLocalizedTerminalTabs(lang: string) {
  return [
    { key: 'positions', label: 'Positions'                                          },
    { key: 'orders',    label: lang === 'en' ? 'Orders'          : 'Ordres'         },
    { key: 'history',   label: lang === 'en' ? 'History'         : 'Historique'     },
    { key: 'account',   label: lang === 'en' ? 'Account Summary' : 'Résumé Compte'  },
  ];
}

export const SYMBOLS: TradingSymbolDef[] = [
  // ── Crypto (Binance USDT) ────────────────────────────────────────────────
  { symbol: 'BTCUSDT',     label: 'BTC/USDT',     type: 'crypto',      spreadKey: 'BTCUSDT'     },
  { symbol: 'ETHUSDT',     label: 'ETH/USDT',     type: 'crypto',      spreadKey: 'ETHUSDT'     },
  { symbol: 'BNBUSDT',     label: 'BNB/USDT',     type: 'crypto',      spreadKey: 'BNBUSDT'     },
  { symbol: 'SOLUSDT',     label: 'SOL/USDT',     type: 'crypto',      spreadKey: 'SOLUSDT'     },
  { symbol: 'XRPUSDT',     label: 'XRP/USDT',     type: 'crypto',      spreadKey: 'XRPUSDT'     },
  { symbol: 'ADAUSDT',     label: 'ADA/USDT',     type: 'crypto',      spreadKey: 'ADAUSDT'     },
  { symbol: 'AVAXUSDT',    label: 'AVAX/USDT',    type: 'crypto',      spreadKey: 'AVAXUSDT'    },
  { symbol: 'DOGEUSDT',    label: 'DOGE/USDT',    type: 'crypto',      spreadKey: 'DOGEUSDT'    },
  { symbol: 'LTCUSDT',     label: 'LTC/USDT',     type: 'crypto',      spreadKey: 'LTCUSDT'     },
  { symbol: 'TRXUSDT',     label: 'TRX/USDT',     type: 'crypto',      spreadKey: 'TRXUSDT'     },
  { symbol: 'LINKUSDT',    label: 'LINK/USDT',    type: 'crypto',      spreadKey: 'LINKUSDT'    },
  { symbol: 'DOTUSDT',     label: 'DOT/USDT',     type: 'crypto',      spreadKey: 'DOTUSDT'     },
  { symbol: 'UNIUSDT',     label: 'UNI/USDT',     type: 'crypto',      spreadKey: 'UNIUSDT'     },
  { symbol: 'ATOMUSDT',    label: 'ATOM/USDT',     type: 'crypto',      spreadKey: 'ATOMUSDT'    },
  { symbol: 'NEARUSDT',    label: 'NEAR/USDT',    type: 'crypto',      spreadKey: 'NEARUSDT'    },
  { symbol: 'APTUSDT',     label: 'APT/USDT',     type: 'crypto',      spreadKey: 'APTUSDT'     },
  { symbol: 'SUIUSDT',     label: 'SUI/USDT',     type: 'crypto',      spreadKey: 'SUIUSDT'     },
  { symbol: 'ARBUSDT',     label: 'ARB/USDT',     type: 'crypto',      spreadKey: 'ARBUSDT'     },
  { symbol: 'OPUSDT',      label: 'OP/USDT',      type: 'crypto',      spreadKey: 'OPUSDT'      },
  { symbol: 'INJUSDT',     label: 'INJ/USDT',     type: 'crypto',      spreadKey: 'INJUSDT'     },
  { symbol: 'MKRUSDT',     label: 'MKR/USDT',     type: 'crypto',      spreadKey: 'MKRUSDT'     },
  { symbol: 'AAVEUSDT',    label: 'AAVE/USDT',    type: 'crypto',      spreadKey: 'AAVEUSDT'    },
  { symbol: 'FILUSDT',     label: 'FIL/USDT',     type: 'crypto',      spreadKey: 'FILUSDT'     },
  { symbol: 'RENDERUSDT',  label: 'RENDER/USDT',  type: 'crypto',      spreadKey: 'RENDERUSDT'  },
  { symbol: 'FETUSDT',     label: 'FET/USDT',     type: 'crypto',      spreadKey: 'FETUSDT'     },
  { symbol: 'WLDUSDT',     label: 'WLD/USDT',     type: 'crypto',      spreadKey: 'WLDUSDT'     },
  { symbol: 'JUPUSDT',     label: 'JUP/USDT',     type: 'crypto',      spreadKey: 'JUPUSDT'     },
  { symbol: 'JTOUSDT',     label: 'JTO/USDT',     type: 'crypto',      spreadKey: 'JTOUSDT'     },
  { symbol: 'ENAUSDT',     label: 'ENA/USDT',     type: 'crypto',      spreadKey: 'ENAUSDT'     },
  { symbol: 'MANAUSDT',    label: 'MANA/USDT',    type: 'crypto',      spreadKey: 'MANAUSDT'    },
  { symbol: 'SANDUSDT',    label: 'SAND/USDT',    type: 'crypto',      spreadKey: 'SANDUSDT'    },
  { symbol: 'GALAUSDT',    label: 'GALA/USDT',    type: 'crypto',      spreadKey: 'GALAUSDT'    },
  { symbol: 'SHIBUSDT',    label: 'SHIB/USDT',    type: 'crypto',      spreadKey: 'SHIBUSDT'    },
  { symbol: 'PEPEUSDT',    label: 'PEPE/USDT',    type: 'crypto',      spreadKey: 'PEPEUSDT'    },
  // ── Forex (Frankfurter.app — BASE/QUOTE ISO format) ──────────────────────
  { symbol: 'EUR/USD',     label: 'EUR/USD',       type: 'forex',       spreadKey: 'EUR/USD'     },
  { symbol: 'GBP/USD',     label: 'GBP/USD',       type: 'forex',       spreadKey: 'GBP/USD'     },
  { symbol: 'USD/JPY',     label: 'USD/JPY',       type: 'forex',       spreadKey: 'USD/JPY'     },
  { symbol: 'USD/CHF',     label: 'USD/CHF',       type: 'forex',       spreadKey: 'USD/CHF'     },
  { symbol: 'AUD/USD',     label: 'AUD/USD',       type: 'forex',       spreadKey: 'AUD/USD'     },
  { symbol: 'USD/CAD',     label: 'USD/CAD',       type: 'forex',       spreadKey: 'USD/CAD'     },
  { symbol: 'NZD/USD',     label: 'NZD/USD',       type: 'forex',       spreadKey: 'NZD/USD'     },
  { symbol: 'EUR/GBP',     label: 'EUR/GBP',       type: 'forex',       spreadKey: 'EUR/GBP'     },
  { symbol: 'EUR/JPY',     label: 'EUR/JPY',       type: 'forex',       spreadKey: 'EUR/JPY'     },
  { symbol: 'EUR/CHF',     label: 'EUR/CHF',       type: 'forex',       spreadKey: 'EUR/CHF'     },
  { symbol: 'EUR/AUD',     label: 'EUR/AUD',       type: 'forex',       spreadKey: 'EUR/AUD'     },
  { symbol: 'EUR/CAD',     label: 'EUR/CAD',       type: 'forex',       spreadKey: 'EUR/CAD'     },
  { symbol: 'GBP/JPY',     label: 'GBP/JPY',       type: 'forex',       spreadKey: 'GBP/JPY'     },
  { symbol: 'GBP/CHF',     label: 'GBP/CHF',       type: 'forex',       spreadKey: 'GBP/CHF'     },
  { symbol: 'GBP/AUD',     label: 'GBP/AUD',       type: 'forex',       spreadKey: 'GBP/AUD'     },
  { symbol: 'GBP/CAD',     label: 'GBP/CAD',       type: 'forex',       spreadKey: 'GBP/CAD'     },
  { symbol: 'AUD/JPY',     label: 'AUD/JPY',       type: 'forex',       spreadKey: 'AUD/JPY'     },
  { symbol: 'CAD/JPY',     label: 'CAD/JPY',       type: 'forex',       spreadKey: 'CAD/JPY'     },
  { symbol: 'CHF/JPY',     label: 'CHF/JPY',       type: 'forex',       spreadKey: 'CHF/JPY'     },
  { symbol: 'NZD/JPY',     label: 'NZD/JPY',       type: 'forex',       spreadKey: 'NZD/JPY'     },
  { symbol: 'AUD/CAD',     label: 'AUD/CAD',       type: 'forex',       spreadKey: 'AUD/CAD'     },
  { symbol: 'AUD/NZD',     label: 'AUD/NZD',       type: 'forex',       spreadKey: 'AUD/NZD'     },
  { symbol: 'USD/MXN',     label: 'USD/MXN',       type: 'forex',       spreadKey: 'USD/MXN'     },
  { symbol: 'USD/SGD',     label: 'USD/SGD',       type: 'forex',       spreadKey: 'USD/SGD'     },
  { symbol: 'USD/NOK',     label: 'USD/NOK',       type: 'forex',       spreadKey: 'USD/NOK'     },
  { symbol: 'USD/SEK',     label: 'USD/SEK',       type: 'forex',       spreadKey: 'USD/SEK'     },
  { symbol: 'USD/ZAR',     label: 'USD/ZAR',       type: 'forex',       spreadKey: 'USD/ZAR'     },
  // ── Matières premières (Twelve Data) ─────────────────────────────────────
  { symbol: 'XAU/USD',    label: 'Gold (XAU)',      type: 'commodities', spreadKey: 'XAU/USD'    },
  { symbol: 'XAG/USD',    label: 'Silver (XAG)',    type: 'commodities', spreadKey: 'XAG/USD'    },
  { symbol: 'WTI/USD',    label: 'WTI Oil',         type: 'commodities', spreadKey: 'WTI/USD'    },
  { symbol: 'BRENT/USD',  label: 'Brent Crude',     type: 'commodities', spreadKey: 'BRENT/USD'  },
  { symbol: 'XPT/USD',    label: 'Platinum (XPT)',  type: 'commodities', spreadKey: 'XPT/USD'    },
  { symbol: 'XPD/USD',    label: 'Palladium (XPD)', type: 'commodities', spreadKey: 'XPD/USD'    },
  { symbol: 'NG/USD',     label: 'Natural Gas',     type: 'commodities', spreadKey: 'NG/USD'     },
  { symbol: 'COPPER/USD', label: 'Copper',          type: 'commodities', spreadKey: 'COPPER/USD' },
  // ── Actions US (Twelve Data) ──────────────────────────────────────────────
  { symbol: 'AAPL',   label: 'Apple',            type: 'stocks',      spreadKey: 'AAPL'   },
  { symbol: 'MSFT',   label: 'Microsoft',        type: 'stocks',      spreadKey: 'MSFT'   },
  { symbol: 'NVDA',   label: 'NVIDIA',           type: 'stocks',      spreadKey: 'NVDA'   },
  { symbol: 'GOOGL',  label: 'Alphabet',         type: 'stocks',      spreadKey: 'GOOGL'  },
  { symbol: 'AMZN',   label: 'Amazon',           type: 'stocks',      spreadKey: 'AMZN'   },
  { symbol: 'META',   label: 'Meta',             type: 'stocks',      spreadKey: 'META'   },
  { symbol: 'TSLA',   label: 'Tesla',            type: 'stocks',      spreadKey: 'TSLA'   },
  { symbol: 'NFLX',   label: 'Netflix',          type: 'stocks',      spreadKey: 'NFLX'   },
  { symbol: 'AMD',    label: 'AMD',              type: 'stocks',      spreadKey: 'AMD'    },
  { symbol: 'AVGO',   label: 'Broadcom',         type: 'stocks',      spreadKey: 'AVGO'   },
  { symbol: 'ORCL',   label: 'Oracle',           type: 'stocks',      spreadKey: 'ORCL'   },
  { symbol: 'ADBE',   label: 'Adobe',            type: 'stocks',      spreadKey: 'ADBE'   },
  { symbol: 'CRM',    label: 'Salesforce',       type: 'stocks',      spreadKey: 'CRM'    },
  { symbol: 'UBER',   label: 'Uber',             type: 'stocks',      spreadKey: 'UBER'   },
  { symbol: 'PYPL',   label: 'PayPal',           type: 'stocks',      spreadKey: 'PYPL'   },
  { symbol: 'INTC',   label: 'Intel',            type: 'stocks',      spreadKey: 'INTC'   },
  { symbol: 'QCOM',   label: 'Qualcomm',         type: 'stocks',      spreadKey: 'QCOM'   },
  { symbol: 'MU',     label: 'Micron',           type: 'stocks',      spreadKey: 'MU'     },
  { symbol: 'JPM',    label: 'JPMorgan',         type: 'stocks',      spreadKey: 'JPM'    },
  { symbol: 'GS',     label: 'Goldman Sachs',    type: 'stocks',      spreadKey: 'GS'     },
  { symbol: 'BAC',    label: 'Bank of America',  type: 'stocks',      spreadKey: 'BAC'    },
  { symbol: 'MS',     label: 'Morgan Stanley',   type: 'stocks',      spreadKey: 'MS'     },
  { symbol: 'WFC',    label: 'Wells Fargo',      type: 'stocks',      spreadKey: 'WFC'    },
  { symbol: 'V',      label: 'Visa',             type: 'stocks',      spreadKey: 'V'      },
  { symbol: 'MA',     label: 'Mastercard',       type: 'stocks',      spreadKey: 'MA'     },
  { symbol: 'AXP',    label: 'Amex',             type: 'stocks',      spreadKey: 'AXP'    },
  { symbol: 'BLK',    label: 'BlackRock',        type: 'stocks',      spreadKey: 'BLK'    },
  { symbol: 'C',      label: 'Citigroup',        type: 'stocks',      spreadKey: 'C'      },
  { symbol: 'BRK.B',  label: 'Berkshire B',      type: 'stocks',      spreadKey: 'BRK.B'  },
  { symbol: 'WMT',    label: 'Walmart',          type: 'stocks',      spreadKey: 'WMT'    },
  { symbol: 'COST',   label: 'Costco',           type: 'stocks',      spreadKey: 'COST'   },
  { symbol: 'MCD',    label: "McDonald's",       type: 'stocks',      spreadKey: 'MCD'    },
  { symbol: 'SBUX',   label: 'Starbucks',        type: 'stocks',      spreadKey: 'SBUX'   },
  { symbol: 'NKE',    label: 'Nike',             type: 'stocks',      spreadKey: 'NKE'    },
  { symbol: 'PG',     label: 'P&G',              type: 'stocks',      spreadKey: 'PG'     },
  { symbol: 'KO',     label: 'Coca-Cola',        type: 'stocks',      spreadKey: 'KO'     },
  { symbol: 'PEP',    label: 'PepsiCo',          type: 'stocks',      spreadKey: 'PEP'    },
  { symbol: 'PM',     label: 'Philip Morris',    type: 'stocks',      spreadKey: 'PM'     },
  { symbol: 'JNJ',    label: 'J&J',              type: 'stocks',      spreadKey: 'JNJ'    },
  { symbol: 'PFE',    label: 'Pfizer',           type: 'stocks',      spreadKey: 'PFE'    },
  { symbol: 'MRK',    label: 'Merck',            type: 'stocks',      spreadKey: 'MRK'    },
  { symbol: 'ABBV',   label: 'AbbVie',           type: 'stocks',      spreadKey: 'ABBV'   },
  { symbol: 'UNH',    label: 'UnitedHealth',     type: 'stocks',      spreadKey: 'UNH'    },
  { symbol: 'LLY',    label: 'Eli Lilly',        type: 'stocks',      spreadKey: 'LLY'    },
  { symbol: 'TMO',    label: 'Thermo Fisher',    type: 'stocks',      spreadKey: 'TMO'    },
  { symbol: 'GILD',   label: 'Gilead',           type: 'stocks',      spreadKey: 'GILD'   },
  { symbol: 'XOM',    label: 'ExxonMobil',       type: 'stocks',      spreadKey: 'XOM'    },
  { symbol: 'CVX',    label: 'Chevron',          type: 'stocks',      spreadKey: 'CVX'    },
  { symbol: 'SLB',    label: 'SLB',              type: 'stocks',      spreadKey: 'SLB'    },
  { symbol: 'COP',    label: 'ConocoPhillips',   type: 'stocks',      spreadKey: 'COP'    },
  { symbol: 'OXY',    label: 'Occidental',       type: 'stocks',      spreadKey: 'OXY'    },
  { symbol: 'BA',     label: 'Boeing',           type: 'stocks',      spreadKey: 'BA'     },
  { symbol: 'CAT',    label: 'Caterpillar',      type: 'stocks',      spreadKey: 'CAT'    },
  { symbol: 'GE',     label: 'GE',               type: 'stocks',      spreadKey: 'GE'     },
  { symbol: 'HON',    label: 'Honeywell',        type: 'stocks',      spreadKey: 'HON'    },
  { symbol: 'LMT',    label: 'Lockheed Martin',  type: 'stocks',      spreadKey: 'LMT'    },
  { symbol: 'RTX',    label: 'Raytheon',         type: 'stocks',      spreadKey: 'RTX'    },
  { symbol: 'SPY',    label: 'S&P 500 ETF',      type: 'stocks',      spreadKey: 'SPY'    },
  { symbol: 'QQQ',    label: 'Nasdaq 100 ETF',   type: 'stocks',      spreadKey: 'QQQ'    },
  { symbol: 'DIA',    label: 'Dow Jones ETF',    type: 'stocks',      spreadKey: 'DIA'    },
  { symbol: 'IWM',    label: 'Russell 2000 ETF', type: 'stocks',      spreadKey: 'IWM'    },
  { symbol: 'GLD',    label: 'Gold ETF',         type: 'stocks',      spreadKey: 'GLD'    },
  { symbol: 'TLT',    label: 'Bonds ETF',        type: 'stocks',      spreadKey: 'TLT'    },
  { symbol: 'XLF',    label: 'Finance ETF',      type: 'stocks',      spreadKey: 'XLF'    },
  { symbol: 'XLK',    label: 'Tech ETF',         type: 'stocks',      spreadKey: 'XLK'    },
  { symbol: 'ARKK',   label: 'ARK Innovation',   type: 'stocks',      spreadKey: 'ARKK'   },
];

export const TERMINAL_TABS = [
  { key: 'positions', label: 'Positions'     },
  { key: 'orders',    label: 'Orders'        },
  { key: 'history',   label: 'History'       },
  { key: 'account',   label: 'Account Summary' },
];
