// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvcrtolqqkdfjnwdqrgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Y3J0b2xxcWtkZmpud2RxcmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzNDM2NDAsImV4cCI6MjA5NTkxOTY0MH0.5EOy_QKSK6ldIem4Ps3FWkP7fDcxDrAPY9vS-t4m2kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});