// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exoisrhuacqeltaucwhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4b2lzcmh1YWNxZWx0YXVjd2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzMDUxNTAsImV4cCI6MjA5Nzg4MTE1MH0.8nWuwUXvdlMTcE61J9wG2fQYRGmHV329vO0iwZTcmRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});